### PR TITLE
Fixed resizing issue.

### PR DESCRIPTION
**Pull request by jdscolam**
All images are appropriately resized, and updated in the background, so they are the appropriate size when rotated to.

### CODE REVIEW

**Comment by jdscolam** [comment]
Just wanted to know if you were planning on merging this PR :).

**Comment by rprovost** [comment]
Sorry. Took a look a little earlier and saw a lot of change on indentation and wanted to comment.

**Comment by jdscolam** [comment]
Sure!  Give me a few.

**Comment by jdscolam** [comment]
Alright, should be fixed.

**Comment by rprovost** [comment]
This looks good to me.

**Pull request merged**
